### ISSUE TITLE
add new instruction 界面，使用缺省这个勾选项放在两个期权选择中间

### ISSUE THREAD

**Issue by zhukevin** [zhukevin/open#65]
而不是第二个后面，tab 键前后操作不方便。缺省选中，我可以撤掉或者索性不要这个东东
直接缺省，我需要就改否则就接受缺省

**Comment by zhukevin** [comment]
我是说 liquid leg auto selction

**Comment by bob-long** [comment]
我调整一下放到页面开始位置
