### ISSUE TITLE
下了同样的两单，第二单把第一单取消了

### ISSUE THREAD

**Issue by zhukevin** [zhukevin/open#74]
价格不同

我们期望的行为是什么样子？难道不是两单一起挂着？ 我忘记了

**Comment by bob-long** [comment]
第二单把第一单取消了的意思是什么？

**Comment by zhukevin** [comment]
就是第一单报的单被撤了
换成新的了 （期望两单都挂着）

**Comment by bob-long** [comment]
每个指令都是单独处理的，前后两单理论上不会有影响，除非是开仓方向是反的，不过那也是在成交之后才会反映
