### ISSUE TITLE
成交价格与预设不一致

### ISSUE THREAD

**Issue by zhukevin** [zhukevin/open#76]
![image](https://user-images.githubusercontent.com/11344079/104684475-faae7400-56ad-11eb-969c-9a92449d93f5.png)
liquid 价格根本不是0.04 （400） 而是416/418

**Comment by bob-long** [comment]
不要看这里的价格，这个价格不是实时更新的，我还没来得及写这个逻辑

**Comment by zhukevin** [comment]
一开始我们设定的是这样

![image](https://user-images.githubusercontent.com/11344079/104992723-78d48880-59d6-11eb-89d2-532d94a7c931.png)

**Comment by zhukevin** [comment]
实际成交是这样

![image](https://user-images.githubusercontent.com/11344079/104992765-91dd3980-59d6-11eb-963e-2117b25e6491.png)

**Comment by zhukevin** [comment]
![image](https://user-images.githubusercontent.com/11344079/105118459-4cc31100-5a83-11eb-9ddb-da4440a9c83c.png)

**Comment by zhukevin** [comment]
上面是成交记录。你看看。 对冲单是590多成交的。
我们的单是：我们期望是560多成交。 如果对冲价涨到了590多，那么我们挂单应该上调，满足combo price

![image](https://user-images.githubusercontent.com/11344079/105118515-6ebc9380-5a83-11eb-815f-f842b7b86344.png)

**Comment by bob-long** [comment]
这个还是个价格跟随的问题而不是下单价格不匹配问题。

我重新发布了一版5.8(版本号没升级)，但是后台逻辑更新了一下，可以再试一次，看是否illiquid leg价格跟随。
