### ISSUE TITLE
US期权相关数据计算和统计

### ISSUE THREAD

**Issue by zjzsu2000** [zhukevin/open#8]
修改计算程序，增加美股的IntTagPackage：
包括
Maxpain_PVT.D
TotalVega_PVT.D
VIX_PVT.D

并统计目前小样本数据的数值范围，为转换成char做准备

**Comment by zjzsu2000** [comment]
1.完成了计算功能并修改了部分US数据DataImport中的bug；
2.生成了相关的Int数据并保存在data5中；
3.server端读取并在前端数据查询窗口顺利显示；
4.server端新增函数，在读取数据时候对数据进行统计并打印。

**Comment by zjzsu2000** [comment]
510050__PVT.M.BAR openValues low:2.246,  high : 3.641
510050__PVT.M.BAR closeValues low:2.246,  high : 3.643
510050__PVT.M.BAR highValues low:2.247,  high : 3.643
510050__PVT.M.BAR lowValues low:2.246,  high : 3.641
510050__PVT.M.BAR volumeValues low:100,  high : 208095359
510050_*_PVT.M.OC openInterestValues low:0,  high : 656795
510050_*_PVT.M.OC volumeValues low:0,  high : 64503
510050_RFR_PVT.M low:0.02205,  high : 0.04932
510050_*.PCP_PVT.M.OG deltaValues low:-1.0,  high : 1.0
510050_*.PCP_PVT.M.OG gammaValues low:9.0E-5,  high : 290.446437
510050_*.PCP_PVT.M.OG thetaValues low:-0.023612,  high : 1.84E-4
510050_*.PCP_PVT.M.OG ivValues low:0.005196,  high : 2.443106
510050_*.PCP_PVT.M.OG vegaValues low:7.0E-6,  high : 1.078888
510050_RFR1_PVT.M low:0.02205,  high : 0.04932
510050_IVIXA_PVT.M low:9.644394,  high : 74.342214
510050_IVIX_PVT.M low:11.918265,  high : 41.009185
510050_IVIXS_PVT.M low:12.971286,  high : 2147.483647
510050_PCPIU_PVT.M low:0.0,  high : 3.55609
510050_Maxpain_PVT.M low:2.049999,  high : 3.8
SPY__PVT.D.BAR openValues low:187.49,  high : 213.24
SPY__PVT.D.BAR closeValues low:187.27,  high : 213.5
SPY__PVT.D.BAR highValues low:189.74,  high : 213.78
SPY__PVT.D.BAR lowValues low:182.4,  high : 212.91
SPY__PVT.D.BAR volumeValues low:56395600,  high : 507244300
SPY_*_PVT.D.OC openInterestValues low:0,  high : 473858
SPY_*_PVT.D.OC volumeValues low:0,  high : 666759
SPY_*.Mid_PVT.D.OG deltaValues low:-1.0,  high : 1.0
SPY_*.Mid_PVT.D.OG gammaValues low:0.0,  high : 1.305319
SPY_*.Mid_PVT.D.OG thetaValues low:-1.002578,  high : 0.002034
SPY_*.Mid_PVT.D.OG ivValues low:0.025756,  high : 3.502503
SPY_*.Mid_PVT.D.OG vegaValues low:9.0E-6,  high : 141.600699
SPY_TotalVega_PVT.D low:-2144.33172,  high : 2142.746298
SPY_Maxpain_PVT.D low:105.0,  high : 212.5
SPY_VIX_PVT.D low:12.250344,  high : 37.199802
QQQ__PVT.D.BAR openValues low:94.23,  high : 114.02
QQQ__PVT.D.BAR closeValues low:98.09,  high : 114.02
QQQ__PVT.D.BAR highValues low:100.95,  high : 114.39
QQQ__PVT.D.BAR lowValues low:84.74,  high : 113.58
QQQ__PVT.D.BAR volumeValues low:13543800,  high : 150829900
QQQ_*_PVT.D.OC openInterestValues low:0,  high : 104668
QQQ_*_PVT.D.OC volumeValues low:0,  high : 118983
QQQ_*.Mid_PVT.D.OG deltaValues low:-1.0,  high : 1.0
QQQ_*.Mid_PVT.D.OG gammaValues low:2.0E-6,  high : 1.351844
QQQ_*.Mid_PVT.D.OG thetaValues low:-0.506038,  high : 8.25E-4
QQQ_*.Mid_PVT.D.OG ivValues low:0.034089,  high : 1.707796
QQQ_*.Mid_PVT.D.OG vegaValues low:0.001025,  high : 59.9965
QQQ_TotalVega_PVT.D low:-2139.806722,  high : 2146.378986
QQQ_Maxpain_PVT.D low:100.5,  high : 113.0
QQQ_VIX_PVT.D low:13.520058,  high : 41.989022

**Comment by zhukevin** [comment]
已完成
